### PR TITLE
Create header-text-button-image.html

### PR DESCRIPTION
**Pull request by coditive-tomek-l**

### CODE REVIEW

**Comment by coditive-tomek-l** [comment]
Big question is the image file and it's URL, I'm not sure if it will work at all.

**Comment by coditive-adam-s** [comment]
> 

@coditive-tomek-l, 
I've checked the pattern and it works perfectly. The image file is available under the URL belonging to the system where the pattern was created(https://staging.coditive.com) and it's displayed inside the pattern via this URL and will be displayed correctly as long as it is available at this URL.

However, currently, the resource used as an image is under the protected URL, which means the image will not be displayed for the users who don't have the access to our staging site.

I think we need to create a place where we will be able to store public resources which we will be using inside the patterns.

**Review by coditive-adam-s — CHANGES_REQUESTED** [review]
The URL for the image is pointing to our staging site, which means the image will not be displayed to anyone who doesn't have access to our staging site. We should store all assets for the patterns publicly.

**Review by coditive-pawel-m — APPROVED** [review]
LGTM

**Pull request merged**
